config/routes.rb
Rails.application.routes.draw do

  root      'kittens#index'
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord

  validates :name,     presence: true
  validates :age,      presence: true,
                       numericality: { only_integer: true,
                                   less_than: 16 }
  validates :cuteness, presence: true,
                       numericality: { only_integer: true,
                                       greater_than: 0,
                                       less_than_or_equal_to: 10 }
  validates :softness, presence: true,
                       numericality: { only_integer: true,
                                       greater_than: 0,
                                       less_than_or_equal_to: 10 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render :json => @kittens }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = "Way to go champ now you have a new fucking kitten"
      redirect_to @kitten
    else
      render 'new'
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update_attributes(kitten_params)
      flash[:success] = "You got it sport, your kitten's all different now"
      redirect_to @kitten
    else
      render 'edit'
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @kitten}
    end
  end

  def destroy
    Kitten.find(params[:id]).destroy
    flash[:success] = "Kitten was destroyed, which is fine because it's an abstract fucking concept for the purposes of this exercise, fuck"
    redirect_to root_url
  end

  private

    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_kitten.html.erb
<li>
  <b><%= link_to kitten.name, kitten %></b>, <%= kitten.age %> |
  Cuteness: <%= kitten.cuteness %>/10 |
  Softness: <%= kitten.softness %>/10 |
  <%= link_to "REMOVE THIS KITTEN", kitten, method: :delete %>
</li>

app/views/kittens/edit.html.erb
<h2>Change your fucking kitten</h2>

<%= render 'shared/kitten_form' %>

<%= link_to "REMOVE THIS KITTY", @kitten, method: :delete %>

app/views/kittens/index.html.erb
<h2>Literally every fucking kitten</h2>

<%= render @kittens %>

<br />
<%= link_to "Invite a kitten to this party", new_kitten_path %>

app/views/kittens/new.html.erb
<h2>New fucking kitten</h2>

<%= render 'shared/kitten_form' %>

app/views/kittens/show.html.erb
<h2><%= @kitten.name %>'s fucking page</h2>

<h3><%= pluralize(@kitten.age, "year") %> old</h3>
<h3><%= @kitten.cuteness %> / 10 on cuteness</h3>
<h3><%= @kitten.softness %> / 10 on softness</h3>

<%= link_to "Check out all the kittens", kittens_path %> |
<%= link_to "Change this kitten", edit_kitten_path(@kitten) %> |
<%= link_to "REMOVE THIS KITTEN", @kitten, method: :delete %>

app/views/layouts/_footer.html.erb
<div class="footer">
  This page was inspired by <a href="http://bettermotherfuckingwebsite.com">bettermotherfuckingwebsite.com</a> and <a href="http://txti.es">txti</a>
  and made by <a href="https://www.github.com/charlesharries">me.</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>So many goddamn kittens</h1>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error-explanation">
    <div class="alert alert-danger">
      This form contains <%= pluralize(object.errors.count, "error") %>:
    </div>
    <ul>
      <% object.errors.full_messages.each do |error| %>
        <li class="alert alert-danger"><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_kitten_form.html.erb
<%= form_for @kitten do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name %><br />

  <%= f.label :age %>
  <%= f.text_field :age %><br />

  <%= f.label :cuteness %>
  <%= f.text_field :cuteness %><br />

  <%= f.label :softness %>
  <%= f.text_field :softness %><br />

  <%= f.submit "Go hog wild bud" %>

<% end %>